### PR TITLE
Changes to improve the accessibility

### PR DESCRIPTION
**Pull request by felixzapata**
Hi, maybe this should be in a branch "step-13"  or "step-a11y". It is possible that I make more updates to improve the accessibility of the example project.

At the moment in this pull request, and based on the idea of @marcysutton, I've changed the mobile filter to inform the user about the number of items found.

Later I will update the phones list to inform the user about changes in the order select control, etc..

Regards.

### CODE REVIEW

**Comment by felixzapata** [comment]
The tests fail because the script try to checkout a branch with a name "step-xxx". But I think that for the moment, this changes should be in a diferent branch. What do you think?

**Comment by felixzapata** [comment]
I´ve update the pull request with:

- added angular-aria.
- added headings to the mobile details.
- set css to see the focus when the image detail receives the focus.
- added a "hidden" message to inform about the image details.

Regards

**Comment by gkalpak** [comment]
@felixzapata, thx for working on this. We are in the middle of a (major-ish) rewrite of the tutorial, so you might want to wait for a few days (until it gets merged).

I can ping you then, so you can rebase your PR and adapt it to the new app structure.

**Comment by felixzapata** [comment]
ok @gkalpak, meanwhile maybe I will continue working on it.

**Comment by felixzapata** [comment]
2016-05-27 9:39 GMT+02:00 googlebot <notifications@github.com>:

**Comment by felixzapata** [comment]
@gkalpak hi, I think there has been a problem with this pull request. I updated it with a new commit after rebase with my original branch for this change but there more commits and files changes. 

So it is possible that this PR is totally unfunctional and it will be better, when you have the new app, to create a new one with my original changes.

Sorry for the inconveniences

**Comment by gkalpak** [comment]
@felixzapata, the new tutorial version was launched earlier this week.

Unfortunately, due to how the tutorial is setup (each step is a commit) and the major-ish restructuring of the application code organization, I am afraid you it would be simpler to close this PR, update you fork with the latest changes and open a new one (after applying your changes on top of the current version).

As you mentioned above, I suggest adding an extra step (e.g. after animations), that deals with ARIA, i.e. briefly explains what it is, why we should care and then how we can incorporate it into an Angular app (and how the awesome `ngAria` module makes it pretty painless) :smiley:

**Comment by felixzapata** [comment]
@scheglov I'm agree ;) I will create another PR later with the new tutorial

**Comment by gkalpak** [comment]
<SUB>Who's @scheglov ? 😛 </SUB>

**Comment by felixzapata** [comment]
oppps ;) fixed

**Pull request closed without merging**
