### PR TITLE
chore(CI): fix "auto-update" Jenkins job

### PR DESCRIPTION
**Pull request by gkalpak**
The job is currently failing, because the Node.js version used in not compatible with some of our dependencies (e.g. Protractor).
The added `jenkins.sh` script is going to be executed by https://ci.angularjs.org/job/angular-phonecat%20auto-update/.

### CODE REVIEW

**Comment by gkalpak** [comment]
After merging this, we should update https://ci.angularjs.org/job/angular-phonecat%20auto-update/ to use run `scripts/private/jenkins.sh`.

/cc @petebacondarwin

**Comment by petebacondarwin** [comment]
I fear that this will also fall foul of the fact that `nvm install` returns an error code if the version is already installed

**Comment by gkalpak** [comment]
@petebacondarwin, I copied the nvm stuff from ng1's jenkins scripts. How come it works there?

**Comment by petebacondarwin** [comment]
Well let's give it a go, eh?

**Comment by petebacondarwin** [comment]
Landed with tweaks: https://ci.angularjs.org/job/angular-phonecat%20auto-update/18634/console

**Comment by gkalpak** [comment]
(Merged as 6b930ac.)

**Pull request closed without merging**
