### PR TITLE
feat: fast-forward the tutorial to the post-1.5.0 era

### LINKED ISSUE #198: Tutor step 4: fogot "query.clear();" in e2e test listing.
I'm learning angularjs and found in tutorial step-4 skip command "query.clear();" before "query.sendKeys('tablet');" in listing for "test/e2e/scenarios.js" because of that this test in Firefox isn't passing.

### LINKED ISSUE #214: Protractor fails on 5th test listed in scenarios.js
Just installed phonecat tutorial, node.js etc but when I run `npm run protractor` the 5th test seems to fail virtually every time - but not always. I'm running this on a fairly old laptop (using Lubuntu) so I wonder if that's the issue.

Here's the error in the terminal:

```
selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /home/david/angular-phonecat
> protractor test/protractor-conf.js

Using ChromeDriver directly...
....F..

Failures:

  1) PhoneCat App Phone detail view should display nexus-s page
   Message:
     Expected '' to be 'Nexus S'.
   Stacktrace:
     Error: Failed expectation
    at [object Object].<anonymous> (/home/david/angular-phonecat/test/e2e/scenarios.js:84:59)

Finished in 19.212 seconds
7 tests, 11 assertions, 1 failure


npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.13.0-39-generic
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! cwd /home/david/angular-phonecat
npm ERR! node -v v0.10.33
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/david/angular-phonecat/npm-debug.log
npm ERR! not ok code 0
```

If I comment out the 5th test within the scenarios.js file, shown below, then the rest of the tests succeed everytime:
```
it('should display nexus-s page', function() {
    expect(element(by.binding('phone.name')).getText()).toBe('Nexus S');
});
```

### LINKED ISSUE #224: Problems running server
Hi, I'm getting the following error when I run ```npm start``` in the step-0 branch.
```
> angular-phonecat@0.0.0 prestart /Users/johnmacaluso/code/angular-phonecat
> npm install

npm WARN package.json karma-chrome-launcher@0.1.4 No README data

> angular-phonecat@0.0.0 postinstall /Users/johnmacaluso/code/angular-phonecat
> bower install


> angular-phonecat@0.0.0 start /Users/johnmacaluso/code/angular-phonecat
> http-server -a 0.0.0.0 -p 8000

sh: http-server: command not found

npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 127
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 start script.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 13.4.0
npm ERR! command "node" "/usr/local/bin/npm" "start"
npm ERR! cwd /Users/johnmacaluso/code/angular-phonecat
npm ERR! node -v v0.10.31
npm ERR! npm -v 2.0.0-beta.0
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/johnmacaluso/code/angular-phonecat/npm-debug.log
npm ERR! not ok code 0
```

### LINKED ISSUE #230: `npm run protractor` doesn't work on Mac OS X Yosemite machine
Hi, trying to run protractor on Mac OS X Yosemite, node v0.12.0, npm 2.5.1 I get the following error (notice `[launcher] Error: Could not find chromedriver at /Users/papple/Devel/angular-phonecat/node_modules/protractor/selenium/chromedriver.exe
`):

```bash
angular-phonecat git:(96a9b5b) npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/papple/Devel/angular-phonecat
> npm run update-webdriver


> angular-phonecat@0.0.0 preupdate-webdriver /Users/papple/Devel/angular-phonecat
> npm install

npm WARN package.json karma-chrome-launcher@0.1.7 No README data

> selenium-chromedriver@0.0.2 install /Users/papple/Devel/angular-phonecat/node_modules/selenium-chromedriver
> node install

Downloading http://chromedriver.storage.googleapis.com/2.8/chromedriver_mac32.zip
Saving to /var/folders/41/0fkmgjl13lq332yk4l_fplbm0000gn/T/selenium-chromedriver115112-46057-c53p2z/chromedriver.zip
Receiving...
Received 781K...
Received 1564K...
Received 2346K...
Received 3128K...
Received 3967K...
Received 4749K...
Received 5531K...
Received 6313K...
Received 7096K...
Received 7878K...
Received 8311K total.
/var/folders/41/0fkmgjl13lq332yk4l_fplbm0000gn/T/selenium-chromedriver115112-46057-zqxgoo
Extracting zip contents
Writing location.txt file
Done. chromedriver binary available at /Users/papple/Devel/angular-phonecat/node_modules/selenium-chromedriver/bin/chromedriver

> angular-phonecat@0.0.0 postinstall /Users/papple/Devel/angular-phonecat
> bower install


> angular-phonecat@0.0.0 update-webdriver /Users/papple/Devel/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/papple/Devel/angular-phonecat
> protractor test/protractor-conf.js

util.puts: Use console.log instead
Using ChromeDriver directly...
[launcher] Error: Could not find chromedriver at /Users/papple/Devel/angular-phonecat/node_modules/protractor/selenium/chromedriver.exe

npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/papple/Devel/angular-phonecat/npm-debug.log
```

### LINKED ISSUE #243: `npm run protractor` doesn't work on win7 x64
npm-debug.log  file
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@2.5.1
3 info using node@v0.10.27
4 verbose node symlink D:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 verbose stack Exit status 1
11 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:213:16)
11 verbose stack     at EventEmitter.emit (events.js:98:17)
11 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:14:12)
11 verbose stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
11 verbose stack     at maybeClose (child_process.js:753:16)
11 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
12 verbose pkgid angular-phonecat@0.0.0
13 verbose cwd F:\2.grunt\angular-phonecat
14 error Windows_NT 6.1.7601
15 error argv "D:\\Program Files\\nodejs\\\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
16 error node v0.10.27
17 error npm  v2.5.1
18 error code ELIFECYCLE
19 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
19 error Exit status 1
20 error Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
20 error This is most likely a problem with the angular-phonecat package,
20 error not with npm itself.
20 error Tell the author that this fails on your system:
20 error     protractor test/protractor-conf.js
20 error You can get their info via:
20 error     npm owner ls angular-phonecat
20 error There is likely additional logging output above.
21 verbose exit [ 1, true ]

### LINKED ISSUE #246: npm run protractor` doesn't work on Mac OS X 10.9.5
Seems to work intermittently.  At the very bottom of this page shows a recent successful run of protractor.

I tried this solution-  downloading  https://sites.google.com/a/chromium.org/chromedriver/downloads manualy and copy in  ... /node_modules/protractor/selenium/ directory

It worked one time,  then failed.  Help!
 

npm ERR! Darwin 13.4.0
npm ERR! argv "node" "/usr/local/bin/npm" "run" "protractor"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular-phonecat@0.0.0 protractor script 'protractor test/protractor-conf.js'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     protractor test/protractor-conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/marklovett/angular-phonecat/npm-debug.log
marks-mbp:angular-phonecat marklovett$ nano /Users/marklovett/angular-phonecat/npm-debug.log

Debug log below:

0 info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'run', 'protractor' ]
2 info using npm@2.7.5
3 info using node@v0.12.2
4 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
5 info preprotractor angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info protractor angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec protractor script
10 verbose stack Error: angular-phonecat@0.0.0 protractor: `protractor test/pro$
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/n$
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/n$
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1015:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1$
11 verbose pkgid angular-phonecat@0.0.0

It seems to work intermittently. The last time I ran protractor it worked!
At end of lesson 4, this is what I got:

marks-mbp:angular-phonecat marklovett$ npm run protractor

> angular-phonecat@0.0.0 preprotractor /Users/marklovett/angular-phonecat
> npm run update-webdriver

> angular-phonecat@0.0.0 preupdate-webdriver /Users/marklovett/angular-phonecat
> npm install

> angular-phonecat@0.0.0 postinstall /Users/marklovett/angular-phonecat
> bower install

> angular-phonecat@0.0.0 update-webdriver /Users/marklovett/angular-phonecat
> webdriver-manager update

selenium standalone is up to date.
chromedriver is up to date.

> angular-phonecat@0.0.0 protractor /Users/marklovett/angular-phonecat
> protractor test/protractor-conf.js

util.puts: Use console.log instead
Using ChromeDriver directly...
..

Finished in 3.871 seconds
2 tests, 5 assertions, 0 failures

### LINKED ISSUE #252: protractor fails invalid chromedriver
c:\Users\cloidjgreen\WebstormProjects\angular-phonecat\node_modules\protractor\lib\driverProviders\local.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at c:\Users\cloidjgreen\WebstormProjects\angular-phonecat\node_modules\protractor\selenium
\chromedriver.exe

There is a chromedriver_2.10.zip downloaded but it will not open.  Seems to be corrupted

### LINKED ISSUE #277: testing error - addMatchers is not a function
I'm following the tutorial to learn how to use Angular. But I am getting this error when I try run the npm test command:

<code>
PhoneCat controllers PhoneListCtrl should create "phones" model with 2 phones fetched from xhr FAILED 
TypeError: this.addMatchers is not a function at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
Expected [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ] to equal [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ].
Error: Expected [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ] to equal [ { name : 'Nexus S' }, { name : 'Motorola DROID' } ].
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:34:28)
Chrome 45.0.2454 (Mac OS X 10.11.0) PhoneCat controllers PhoneListCtrl should set the default value of orderProp model FAILED
TypeError: this.addMatchers is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
Chrome 45.0.2454 (Mac OS X 10.11.0) PhoneCat controllers PhoneDetailCtrl should fetch phone detail FAILED
TypeError: this.addMatchers is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:7:10)
TypeError: expect(...).toEqualData is not a function
at Object.<anonymous> (/Users/alex/Sites/htdocs/angular-phonecat/test/unit/controllersSpec.js:66:27)
</code>

### LINKED ISSUE #286: Step 8 - Tutorial code different than live demo code
In step 8 use template from app/partials/phone-detail.html
And that different from live demo that use http://angular.github.io/angular-phonecat/step-8/app/#/phones

### LINKED ISSUE #295: [Step 5 - 10] ($http) `.success` has been deprecated
Use `.then` instead

### LINKED ISSUE #303: _http_outgoing.js:351       throw new TypeError('The header content contains invalid characters');       ^
## Environment : 
Windows 10 64bit, nodejs 4.3.x and nodejs 5.6.x

## Issue : 
**Trying to connect after starting with "npm start",  http-server die with follwing error.**

```
_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.(anonymous function) [as setHeader] (C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\union\lib\response-stream.js:86:34)
    at serve (C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:146:11)
    at C:\SourceIgloo\0.Studying\AngularJS\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:82:15)
```

## Solution :
**need to upgrade http-server to 0.8.5**

In package.json
```
"http-server": "^0.8.5"
```

### LINKED ISSUE #304: Problem with starting a server
I tried to learn the 1-st step from angular tutorial but I couldn't even start a server.
It starts normally, but when I am going to visit http://127.0.0.1:8000/ it throws me an error. I attached debug.txt here.
Help me please.

[npm-debug.txt](https://github.com/angular/angular-phonecat/files/131377/npm-debug.txt)

### LINKED ISSUE #323: I've got a proplem with protractor
I try to run End to End test npm run protractor. As a result I get error. This is a log:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'protractor' ]
2 info using npm@1.4.3
3 info using node@v0.10.26
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'preprotractor', 'protractor', 'postprotractor' ]
6 info preprotractor angular-phonecat@0.0.0
7 verbose unsafe-perm in lifecycle true
8 info protractor angular-phonecat@0.0.0
9 verbose unsafe-perm in lifecycle true
10 info angular-phonecat@0.0.0 Failed to exec protractor script
11 error angular-phonecat@0.0.0 protractor: `protractor test/protractor-conf.js`
11 error Exit status 8
12 error Failed at the angular-phonecat@0.0.0 protractor script.
12 error This is most likely a problem with the angular-phonecat package,
12 error not with npm itself.
12 error Tell the author that this fails on your system:
12 error     protractor test/protractor-conf.js
12 error You can get their info via:
12 error     npm owner ls angular-phonecat
12 error There is likely additional logging output above.
13 error System Windows_NT 6.2.9200
14 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "protractor"
15 error cwd E:\Users\User\Documents\NetBeansProjects\angular-phonecat
16 error node -v v0.10.26
17 error npm -v 1.4.3
18 error code ELIFECYCLE
19 verbose exit [ 1, true ]

What's the problem?

### LINKED ISSUE #324: Problems with start angular-phonecat Wndows 7
Starting up http-server, serving ./ on port: 8000
Hit CTRL-C to stop the server
[Sun, 10 Apr 2016 15:29:51 GMT] "GET /app/index.html" "Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Geck
o) Chrome/49.0.2623.110 Safari/537.36"
_http_outgoing.js:351
      throw new TypeError('The header content contains invalid characters');
      ^

TypeError: The header content contains invalid characters
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:351:13)
    at ResponseStream.(anonymous function) [as setHeader] (D:\!Projects\Angular\angular-phonecat\node_modules\http-serve
r\node_modules\union\lib\response-stream.js:86:34)
    at serve (D:\!Projects\Angular\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:146:1
1)
    at D:\!Projects\Angular\angular-phonecat\node_modules\http-server\node_modules\ecstatic\lib\ecstatic.js:139:9
    at FSReqWrap.oncomplete (fs.js:82:15)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.0
npm ERR! code ELIFECYCLE
npm ERR! angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
npm ERR! This is most likely a problem with the angular-phonecat package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     http-server -a 0.0.0.0 -p 8000
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-phonecat
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular-phonecat
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\!Projects\Angular\angular-phonecat\npm-debug.log
PS D:\!Projects\Angular\angular-phonecat>
FILE npm-debug:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@2.15.0
3 info using node@v4.4.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart angular-phonecat@0.0.0
6 verbose unsafe-perm in lifecycle true
7 info start angular-phonecat@0.0.0
8 verbose unsafe-perm in lifecycle true
9 info angular-phonecat@0.0.0 Failed to exec start script
10 verbose stack Error: angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at EventEmitter.emit (events.js:172:7)
10 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
10 verbose stack     at emitTwo (events.js:87:13)
10 verbose stack     at ChildProcess.emit (events.js:172:7)
10 verbose stack     at maybeClose (internal/child_process.js:827:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
11 verbose pkgid angular-phonecat@0.0.0
12 verbose cwd D:\!Projects\Angular\angular-phonecat
13 error Windows_NT 6.1.7601
14 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
15 error node v4.4.2
16 error npm  v2.15.0
17 error code ELIFECYCLE
18 error angular-phonecat@0.0.0 start: `http-server -a 0.0.0.0 -p 8000`
18 error Exit status 1
19 error Failed at the angular-phonecat@0.0.0 start script 'http-server -a 0.0.0.0 -p 8000'.
19 error This is most likely a problem with the angular-phonecat package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     http-server -a 0.0.0.0 -p 8000
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs angular-phonecat
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls angular-phonecat
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

### PR DESCRIPTION
**Pull request by gkalpak**
This PR constitutes a major re-structuring of the tutorial app's codebase, aiming at applying established best practices (in terms of file naming/layout and code organization) and utilizing several new features and enhancements (most notably components) introduced in recent versions of Angular (especially v1.5).

Apart from the overall changes, two new chapters were introduced: one on components and one on code organization.

--
In the process, several other things were (incidentally) taken care of, including:

* Dependencies were upgraded to latest versions.
* Animations were polished.
* Outdated links were updated.
* The app's base URL was changed to `/` (instead of `/app/`).
* ...etc...

BTW, I have tested with the following versions on Node (on Windows 10) and everything seems to work fine:

* `0.11.16`
* `4.2.6`
* `4.4.2`
* `5.10.0`

--
This was inspired by (and loosely based on) #289.
Mad props to @teropa for leading the way :)

--
**Note:**
The old version of the tutorial, that is compatible with Angular version 1.4 or older, has been saved in the `pre-v1.5.0-snapshot` branch. The `v1.4.x` version of the tutorial should be pointed to that branch instead of `master`.

--
Related to angular/angular.js#14416.
Related to angular/angular-seed#341.

---
Fixes #198
Fixes #214
Fixes #224
Fixes #230
Fixes #243
Fixes #246
Fixes #252
Fixes #277
Fixes #286
Fixes #295
Fixes #303
Fixes #304
Fixes #323 
Fixes #324

Closes #268
Closes #270
Closes #278
Closes #280
Closes #289
Closes #309
Closes #311
Closes #319

### CODE REVIEW

**Comment by gkalpak** [comment]
This has to get merged simultaneously with corresponding PRs on:

* https://github.com/angular/angular-seed
* https://github.com/angular/angular.js
* (https://github.com/angular/angular.io)

--
Things that should/could be cosidered (potentially after this PR has been merged merged):

- [ ] Make sure the static app on the `gh-pages` branch still works as expected.
- [ ] Adding an "advanced" section at the end, either pointing to resources (e.g. relevant Developer Guide sections) or as subsequent steps. Example topics:
    * Directives/DDO, 2-way/1-way/1-time bindings
    * Forms (+ `ngMessages`)
    * `ngComponentRouter`
    * (multi-slot) transclusion
    * Task runners/Build tools and best practices.
- [ ] Update Travis to Node v5.
- [ ] Minor, but I was wondering if it's best to import the `core` module from the main `phonecatApp` module only, or on a per-view basis.

**Comment by teropa** [comment]
@gkalpak @petebacondarwin The corresponding PR for angular.io is angular.io#1106 where all the relevant changes have been done.

**Comment by rleir** [comment]
gkalpak:post-v1.5.0-update works nicely for me. But first I have to change bower.js; it still calls for angular 1.4.x in some steps (I must be doing something wrong).  

Would it make sense to merge the 16 commits, then sort out the minor glitches?

**Comment by gkalpak** [comment]
@rleir, if you can point out in what steps you see `1.4.x` versions being called, I could look into it.

This (and the related PRs) are still under review - it is important to get them right, because it will be very frustrating for people trying to learn Angular running into random issues (because of a tutorial bug). Plus, this is a little more complicated than usual, because there are several repos affected (angular.js, angular-seed, angular-phonecat and even angular2 docs have a chapter that relies on this), so we need to coordinate.
That said, we are pretty close (although I am sure there will be glitches we will need to sort out later anyway :stuck_out_tongue: )

**Comment by rleir** [comment]
Hi Georgios
In the bower.json. There are 12 versions of this, one for each tutorial step. This confused me, I wanted to do a pull but did not see how to get these versions in git. Explain it to me and I can do a pull.

Yes it is important to get it bug free! It is also important to get it up to date. Newcomers like myself trip up on the changes.
Thanks
Rick

On May 16, 2016 8:28:48 AM EDT, Georgios Kalpakas <notifications@github.com> wrote:
>@rleir, if you can point out in what steps you see `1.4.x` versions
>being called, I could look into it.
>
>This (and the related PRs) are still under review - it is important to
>get them right, because it will be very frustrating for people trying
>to learn Angular running into random issues (because of a tutorial
>bug). Plus, this is a little more complicated than usual, because there
>are several repos affected (angular.js, angular-seed, angular-phonecat
>and even angular2 docs have a chapter that relies on this), so we need
>to coordinate.
>That said, we are pretty close (although I am sure there will be
>glitches we will need to sort out later anyway :stuck_out_tongue: )
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/angular/angular-phonecat/pull/326#issuecomment-219413437

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gkalpak** [comment]
@rleir, phonecat uses an unusual setup, where each step is represented by a separate commit. This is cool when studying the tutorial - not so cool when trying to update it :(
(In a nutshell, you have to rebase and amend the X last commit.)

BTW, we just decided to drop bower in favor of npm (with a post-install script to copy the necessary files from `node_modules/` into `app/lib/` or something).
So, there will be one less tool to worry about.

**Comment by rleir** [comment]
Good plan. I will help by testing.

On May 16, 2016 9:50:01 AM EDT, Georgios Kalpakas <notifications@github.com> wrote:
>@rleir, phonecat uses an unusual setup, where each step is represented
>by a separate commit. This is cool when studying the tutorial - not so
>cool when trying to update it :(
>(In a nutshell, you have to rebase and amend the X last commit.)
>
>BTW, we just decided to drop bower in favor of npm (with a post-install
>script to copy the necessary files from `node_modules/` into `app/lib/`
>or something).
>So, there will be one less tool to worry about.
>
>---
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/angular/angular-phonecat/pull/326#issuecomment-219429358

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gkalpak** [comment]
I ran into several bumps trying to use `npm` instead of `bower`, so we deferred that for a later time.

**Pull request merged**
