### PR TITLE
chore(structure): WIP refactor to Angular style guide conventions

### PR DESCRIPTION
**Pull request by teropa**
Reorganize application code to be more closely aligned
with the Angular Style Guide.

This is for the final version of the app and hasn’t been
factored into steps or into the tutorial text.

1. Folders-by-feature structure: /core, /phone_list, /phone_detail
   https://github.com/johnpapa/angular-styleguide#style-y152
2. App root module depends on feature modules and core module.
   https://github.com/johnpapa/angular-styleguide#style-y165
3. One component per file. Each controller/factory/filter in its own file.
   https://github.com/johnpapa/angular-styleguide#style-y001
4. Feature+type file naming convention.
   https://github.com/johnpapa/angular-styleguide#style-y120
5. Module files, *.module.js for each module.
   https://github.com/johnpapa/angular-styleguide#style-y127
6. Component registration with getters
   https://github.com/johnpapa/angular-styleguide#style-y022
7. Named functions
   https://github.com/johnpapa/angular-styleguide#style-y024
8. Manual injection
   https://github.com/johnpapa/angular-styleguide#style-y091

Related to angular/angular.js#13312
Related to angular/angular.js#13834

### CODE REVIEW

**Comment by teropa** [comment]
@petebacondarwin Here's a more styleguide-compatible version of the final PhoneCat app. I'd love to hear your opinions on a couple of things:

1. Do you think it would make sense to teach this kind of app structure in the tutorial? 
2. Irrespective of (1), would you be willing to include this (or something like this) as a separate branch in the PhoneCat repo so that people who want to follow along with the ng-upgrade tutorial can use it as a starting point?

**Comment by petebacondarwin** [comment]
I like where this is going. I'll try to do a proper review over the weekend.
Can we consider using component directives rather than controllers?

**Comment by teropa** [comment]
Great, thanks!

> Can we consider using component directives rather than controllers?

Yes, I think so! Just pushed a commit that attempts it.

Caveat: Ideally this would use the component router, but not sure if that's doable at this point. Instead using the old router with little template snippets that instantiate the component directives.

Caveat 2: Haven't seen what @johnpapa's style guide for components will look like yet :)

**Comment by Hotell** [comment]
:+1:

**Comment by Hotell** [comment]
I would also recommend to get rid of `ng-app` and use manual bootstrap `angular.bootstrap(...)`

and encapsulate 
```html
<div class="view-container">
    <div ng-view class="view-frame"></div>
</div>
``` 
into an root component 
```html
<phone-cat-app></phone-cat-app>
```

**Comment by petebacondarwin** [comment]
@Hotell that's not a bad idea either.

**Comment by Hotell** [comment]
I'll gladly help with this, because I wanna use this PR as a starting point for showcasing people how to migrate to Typescript + [ngMetadata](https://github.com/ngParty/ng-metadata) and then leveraging ngUpgrade to ng2

**Pull request closed without merging**
