### PR TITLE
chore(package): update script for consistency with `angular-seed`

### PR DESCRIPTION
**Pull request by gkalpak**
Related to https://github.com/angular/angular-seed/pull/343.

### CODE REVIEW

**Comment by gkalpak** [comment]
This is the new commit: https://github.com/angular/angular-phonecat/pull/346/commits/91ee8af33681b95075944463bf8a89360e7891f7

**Comment by petebacondarwin** [comment]
LGTM

**Comment by gkalpak** [comment]
Closed with 37dd5bc.

/fyi @petebacondarwin
I sneaked in another commit 54a2f1e (to avoid deleting the `1.4-*` tags when retagging on master).

**Pull request closed without merging**
